# name: Bonjour
# on:
#   - push
# jobs:
#   dire_bonjour:
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
#       - run: ls -l # Liste les fichier du répertoire courant
#       - run: cat README.md # Affiche le contenu du fichier `README.md` à la base du dépôt


# name: Bonjour
# on:
#   - push
# jobs:
#   dire_bonjour:
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
#       - run: |
#           sudo apt-get update
#           sudo apt-get install -y cowsay          
#       - run: cat README.md | cowsay


# name: Bonjour
# on:
#   - push
# jobs:
#   dire_bonjour:
#     runs-on: ubuntu-22.04
#     container:
#       image: ghcr.io/cicd-lectures/gitpod:latest
#       options: --user=root
#     steps:
#       - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
#       - run: cat README.md | cowsay


# name: Bonjour
# on:
#   - push
# jobs:
#   dire_bonjour:
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
#       - uses: juliangruber/read-file-action@v1
#         id: readfile
#         with:
#           path: ./README.md
#       - uses: Code-Hex/neo-cowsay-action@v1
#         with:
#           message: ${{ steps.readfile.outputs.content }}


# name: Bonjour
# on:
#   - push
# jobs:
#   dire_bonjour:
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
#       - uses: juliangruber/read-file-action@v1
#         id: readfile
#         with:
#           path: ./README.md
#       - uses: Code-Hex/neo-cowsay-action@v1
#         with:
#           message: ${{ steps.readfile.outputs.content }}


name: Vehicle Server CI
on:
  - push
jobs:
  IntegrationContinue :
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses : actions/checkout@v4
      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.x'
      - run: npm ci
      - name: Build application
        run: npm run build
      - name: Run Lint
        run: npm run lint
      - name: List dist output
        run: ls dist/
